name: Build WPF App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x  # Use .NET 9 SDK

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish WPF App
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WPF-App
        path: ./publish
